version: '1'

services:
    g2-festiplan:
        image: webdevops/php-apache-dev:8.2-alpine
        container_name: g2-festiplan
        working_dir: /app/
        ports:
            - 8080:80
        volumes:
            - ./festiplan/:/app/
    g2-festiplan-db:
        image: mysql:8
        container_name: g2-festiplan-db
        environment:
            - MYSQL_USER=server-user
            - MYSQL_DATABASE=festiplan
            - MYSQL_PASSWORD=12AveyronRodezIUT
            - MYSQL_ROOT_PASSWORD=12AveyronRodezIUTJeSuisGroot
        ports:
            - 6612:3306
        volumes:
            - ./sql/:/docker-entrypoint-initdb.d
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
    php-my-admin:
        image: phpmyadmin:latest
        container_name: php-my-admin
        working_dir: /pma/
        depends_on:
            - g2-festiplan-db
        environment:
            - PMA_HOST=g2-festiplan-db
            - PMA_PORT=3306
        ports:
            - 8888:80
