version: '1'

services:
    website:
        image: webdevops/php-apache:8.2-alpine
        container_name: website
        working_dir: /app/
        ports:
            - 9999:80
        volumes:
            - ./:/app/
        profiles:
            - prod
        environment:
            - php.file_uploads=1
    dev-website:
        image: webdevops/php-apache-dev:8.2-alpine
        container_name: dev-website
        working_dir: /app/
        ports:
            - 9999:80
        volumes:
            - ./:/app/
        profiles:
            - dev
            - dev-db
        environment:
            - php.file_uploads=1
    database:
        image: mysql:8
        container_name: database
        environment:
            - MYSQL_DATABASE=festiplan
            - MYSQL_USER=server-user
            - MYSQL_PASSWORD=12AveyronRodezIUT
            - MYSQL_ROOT_PASSWORD=12AveyronRodezIUTJeSuisGroot
        ports:
            - 6612:3306
        volumes:
            - ./sql/:/docker-entrypoint-initdb.d
        profiles:
            - dev-db
            - prod
    php-my-admin-distant:
        image: phpmyadmin:latest
        container_name: php-my-admin-distant
        working_dir: /pma/
        environment:
            - PMA_HOST=saccharun.fr
            - PMA_PORT=6612
        ports:
            - 8888:80
        profiles:
            - dev
    php-my-admin-local:
        image: phpmyadmin:latest
        container_name: php-my-admin-local
        working_dir: /pma/
        environment:
            - PMA_HOST=database
            - PMA_PORT=3306
        ports:
            - 8888:80
        profiles:
            - dev-db
