version: '1'

services:
    website:
        image: webdevops/php-apache-dev:8.2-alpine
        container_name: website
        working_dir: /app/
        ports:
            - 8080:80
        volumes:
            - ./:/app/
        profiles:
            - dev
            - prod
    database:
        image: mysql:8
        container_name: database
        environment:
            - MYSQL_DATABASE=festiplan
            - MYSQL_USER=server-user
            - MYSQL_PASSWORD=12AveyronRodezIUT
            - MYSQL_ROOT_PASSWORD=12AveyronRodezIUTJeSuisGroot
        ports:
            - 6612:3306
        volumes:
            - ./sql/:/docker-entrypoint-initdb.d
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        profiles:
            - dev-db
            - prod
    php-my-admin:
        image: phpmyadmin:latest
        container_name: php-my-admin
        working_dir: /pma/
        environment:
            - PMA_HOST=saccharun.fr
            - PMA_PORT=6612
        ports:
            - 8888:80
        profiles:
            - dev
